USE [CRMS_DEX_VAL]
GO

/****** Object:  StoredProcedure [CROMS].[NLM_GetMaskedRoles]    Script Date: 10/1/2019 4:46:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [CROMS].[NLM_GetMaskedRoles1]   
    @p_fromdate_in datetime,
    @p_todate_in datetime
AS

SELECT DISTINCT PRO_PROTOCOL_NUMBER AS PROTOCOL_NO 
	,PMR_MASKED_ROLE_TYPE  AS ROLE_TYPE_LOV 
	 --PVR_MASKING_DESCRIPTION AS MASKING_DESCRIPTION
		
FROM CROMS.PROTOCOLS PRO
	LEFT  JOIN CROMS.PROTOCOL_VERSIONS PVR ON PRO_ID = PVR_PRO_ID
	LEFT JOIN CROMS.PROTOCOL_MASKED_ROLES PMR ON PVR_ID = PMR_PVR_ID		
WHERE PRO_OVERALL_RECRUIT_STATUS  <> 'Unknown'
	AND PRO_NLM_SEND_YN = 'Y'
	AND PRO_NLM_SEND_WEEKLY_YN = 'Y'
	AND PVR_CURRENT_REVIEW_STATUS = 'Reviewed'	
	AND PRO_LAST_CHANGED_DATE  >= @p_fromdate_in		
	AND PRO_LAST_CHANGED_DATE  < @p_todate_in
	AND PVR_CURRENT_VERSION_YN = 'Y' 
ORDER BY PRO_PROTOCOL_NUMBER



GO


